### ISSUE TITLE
Line up user-facing API across SDKs

### ISSUE THREAD

**Issue by gvdongen** [restatedev/sdk-java#160]
We use different names for oneWayCall, rpc, delayed calls, etc.
We should line up the names across Java / TS handler / TS gRPC

**Comment by slinkydeveloper** [comment]
Regarding one way call/delayed call. In the generated client we generate the following api:

```java
client.oneWay().greet()
client.delayed(Duration).greet()
```

Personally I don't see much the reason to align them renaming to `oneWayCall()`, as they're fundamentally the same name already, one is just more verbose than the other but the "concept name" is still the same. I find the fluent api much nicer without the verbosity of the `call`, as it's redundant: the method is on a service client, so obviously that is a "call" already.

In the `RestateContext` though we retain the verbosity, naming those methods `oneWayCall()` and `delayedCall()`, because the `RestateContext` has a collection of other methods that are not just "call".

Does that makes sense?

**Comment by gvdongen** [comment]
I think we first need to list the differences between the APIs. For example, in the TS handler api its `send` and `rpc` instead of `oneWayCall` and `call`. I list it up tomorrow.

**Comment by tillrohrmann** [comment]
cc @igalshilman

**Comment by gvdongen** [comment]
Also the suspension timeout differs. 30 seconds for TS, 60 seconds for Java

**Comment by slinkydeveloper** [comment]
As it is this one is not actionable now. We have solved most of these already. If you still find inconsistencies, let's open specific issues.
