### ISSUE TITLE
Add a simple java maven template

### ISSUE THREAD

**Issue by igalshilman** [restatedev/sdk-java#392]
We already have few good examples, would be nice to have a clean and simple java maven example

**Comment by slinkydeveloper** [comment]
We have one already: https://github.com/restatedev/examples/tree/main/templates/java-maven

Even spring boot https://github.com/restatedev/examples/tree/main/templates/java-maven-spring-boot and quarkus https://github.com/restatedev/examples/tree/main/templates/java-maven-quarkus

Putting it in this repo might be challenging because of the build setup heavily based on gradle, but we can link it here in the readme perhaps.
